# Generated by Django 4.2.7 on 2025-08-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Product category (optional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.category",
            ),
        ),
    ]
